# Generated by Django 3.0.8 on 2020-07-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_entry', models.CharField(max_length=500)),
                ('dog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_dog_app.DogName')),
            ],
        ),
    ]
