# Generated by Django 3.0.8 on 2020-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dog_photo',
            field=models.ImageField(blank=True, upload_to='photo_img/'),
        ),
    ]
