# Generated by Django 3.0.8 on 2020-07-27 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0003_entry_dog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogname',
            name='date_entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
