# Generated by Django 3.0.8 on 2020-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0004_auto_20200727_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dog_photo',
            field=models.ImageField(blank=True, default=None, upload_to='photo_img/'),
        ),
    ]
