# Generated by Django 3.0.8 on 2020-07-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0005_auto_20200729_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='bio_entry',
            field=models.TextField(),
        ),
    ]
