# Generated by Django 3.0.8 on 2020-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0008_auto_20200730_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogname',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bio_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
