# Generated by Django 3.0.8 on 2020-07-30 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_dog_app', '0009_auto_20200730_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogname',
            name='name',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogname',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bio_entry',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
