# Generated by Django 3.0.8 on 2020-07-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0010_auto_20200730_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dog_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_dog_app.DogName'),
        ),
    ]
