# Generated by Django 3.0.8 on 2020-08-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_dog_app', '0011_auto_20200730_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogname',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='dog_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_dog_app.DogName'),
            preserve_default=False,
        ),
    ]
