# Generated by Django 3.0.8 on 2020-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0014_auto_20200803_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogname',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
