# Generated by Django 3.0.8 on 2020-08-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dog_app', '0016_auto_20200807_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogname',
            name='shared_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='shared_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_entry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
